config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :feeds do
    collection do
        post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    # If the currently logged-in user does not exist, redirect to the login page.
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id=current_user.id
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :content , :image_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'I failed to login'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
     @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
   if action_name == 'new'
     confirm_feeds_path
   elsif action_name == 'edit'
     feed_path
   end
 end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h3>Send with the following contents.</h3>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>Title:<%= @feed.content %></p>
  <p>Content:<%= image_tag @feed.image.url %></p>
  <%= form.submit  "confirm process" %>
<% end %>
<%= link_to 'Return', :back %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Content</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%=image_tag feed.image.url%></td>
        <td><%= feed.content %></td>
          <td><%= feed.user.name %></td>
        <div class="btn-group">
              <td>
          <button type="button" class="btn btn-primary"><%= link_to 'Show', feed %></button>
          <button type="button" class="btn btn-primary"><%= link_to 'Edit', edit_feed_path(feed) %></button>
          <button type="button" class="btn btn-primary"><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<button type="button" class="btn btn-success"><%= link_to 'New Feed', new_feed_path %></button>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="header">
      <div class="first">
        <%= image_tag("facebook.png") %>
      </div>
      <div class="second">
        <%= image_tag("fb.jpeg") %>
      </div>
    </header>

 <% flash.each do |key, value| %>
 <%= content_tag(:div, value, class: "#{key}") %>
 <% end %>
 <% if logged_in? %>
  <button type="button" class="btn btn-info"> <%= link_to "Posts", feeds_path(current_user.id) %>    </button>
  <button type="button" class="btn btn-info"><%= link_to "Profile", user_path(current_user.id) %></button>
  <button type="button" class="btn btn-danger"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
  <% else %>
  <button type="button" class="btn btn-warning"><%= link_to "Sign up", new_user_path %></button>
  <button type="button" class="btn btn-primary"> <%= link_to "Login", new_session_path %></button>
  <% end %>
  <%= yield %>
  <footer class="footer">
    <p>Copyright © 2020 Facebookclone inc, All RIGHTS RESERVED.</p>
  </footer>

 </body>
 </html>

app/views/users/new.html.erb
<h4>Create new account</h4>
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <%= form_with(model: @user, local: true) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :email %>
 <%= f.email_field :email %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>
 <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="button" class="Submit"><%= f.submit "Submit" %></button>
 <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>email: <%= @user.email %></p>